service: reddit-golang-webscrapper

provider:
  region: "us-east-1"
  name: aws
  runtime: go1.x
  timeout: 30

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  scrapper:
    handler: bin/scrapper
    # events:
    #   # every Monday at 03:15 AM
    #   - schedule: cron(15 3 ? * MON *)
    environment:
      S3_FILES_BUCKET: ${env:S3_FILES_BUCKET, self:provider.S3_FILES_BUCKET}