service: reddit-golang-webscraper

provider:
  region: "us-east-1"
  name: aws
  runtime: go1.x
  timeout: 900

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  scraper:
    handler: bin/scraper
    events:
      # mon through fri at 7 AM EST
      # No threads on weekends
      - schedule: cron(0 12 ? * MON-FRI *)
    environment:
      S3_FILES_BUCKET: ${env:S3_FILES_BUCKET, self:provider.S3_FILES_BUCKET}