service: reddit-golang-webscraper

provider:
  region: "us-east-1"
  name: aws
  runtime: go1.x
  timeout: 900

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  scraper:
    handler: bin/scraper
    # events:
    #   # every Monday at 03:15 AM
    #   - schedule: cron(15 3 ? * MON *)
    environment:
      S3_FILES_BUCKET: ${env:S3_FILES_BUCKET, self:provider.S3_FILES_BUCKET}