service: reddit-golang-webscrapper

provider:
  region: "us-east-1"
  name: aws
  runtime: go1.x

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  scrapper:
    handler: bin/scrapper
    environment:
      S3_FILES_BUCKET: ${env:S3_FILES_BUCKET, self:provider.S3_FILES_BUCKET}